# -*- coding: utf-8 -*-
"""Analise_clientes_Cancelamento_cartao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkDqhN3JkaM86_nbmV2wORA1I9hC0UP_
"""

import pandas as pd

tabela = pd.read_csv("/content/drive/MyDrive/ClientesBanco.csv", encoding="latin")
display(tabela)

tabela = tabela.drop("CLIENTNUM", axis=1)
display(tabela)

display(tabela.info())

"""# Agora vamos tratar valores vazios e exibir um resumo das colunas da base de dados"""

tabela = tabela.dropna()
display(tabela.info())

display(tabela.describe().round(1))

"""# Vamos avaliar como está a divisão entre Clientes x Cancelados

"""

qtde_categoria = tabela["Categoria"].value_counts()
display(qtde_categoria)

qtde_categoria_perc = tabela["Categoria"].value_counts(normalize=True)
display(qtde_categoria_perc)



"""# Temos várias formas de descobrir o motivo de cancelamento
### Podemos olhar a comparação entre Clientes e Cancelados em cada uma das colunas da nossa base de dados,para ver se essa informação traz algum insight novo.
"""

import plotly.express as px

grafico = px.histogram(tabela, x="Idade", color="Categoria")
grafico.show()

for coluna in tabela:
  grafico = px.histogram(tabela, x=coluna, color="Categoria")
  grafico.show()



"""# Informações retiradas da análise

#### Pela analise feita nos graficos pode notar que quanto mais produtos contratados um cliente tem, menor a chance dele cancelar.

#### E quanto mais transações e quanto maior o valor de transação,menor a chance dele cancelar.

#### Quanto maior a quantidade de contatos que o cliente teve que fazer, maior á chance de cancelamento.
"""